# SkyRL Configuration: Qwen3 8B on 16x80GB GPUs (GSPO Policy Loss)
# Ablation: Uses GSPO policy loss with sequence_mean reduction
#
# POLICY LOSS: GSPO (Group-wise SPO) with sequence_mean reduction
# Base config: qwen3_8b_16x80GB_binary.yaml
#
# GSPO (Group-wise Sequence Policy Optimization) treats each sequence equally
# in the loss computation, regardless of length. The GSPO paper recommends
# using sequence_mean reduction for stability.
#
# Hardware: 16 GPUs with 80GB VRAM each (e.g., 2x8 H100/A100-80GB or 4x4)
# Model: Qwen3 8B Base (~16GB bf16 weights)
#
# CONTEXT BUDGET (32k total model context):
#   - max_generate_length: 8k tokens (agent responses)
#   - vLLM enforces total context <= max_model_len (32k)
#
# Usage:
#   python -m hpc.launch \
#       --job_type rl \
#       --rl_config qwen3_8b_16x80GB_gspo.yaml \
#       --job_name qwen3_8b_gspo \
#       --train_data '["mlfoundations-dev/your-dataset"]' \
#       --model_path Qwen/Qwen3-8B \
#       --num_nodes 2

# SkyRL entrypoint module
entrypoint: examples.terminal_bench.entrypoints.main_tbench

# Hydra config groups (+ prefix in CLI)
config_groups:
  terminal_bench_config: terminal_bench

# Terminal bench / agentic environment settings
terminal_bench:
  # trials_dir: Directory for Harbor trial artifacts (derived from experiments_dir if null)
  trials_dir: null

  # Harbor configuration - schema-driven mapping to TrialConfig
  # See examples/terminal_bench/harbor_config.py for full list of supported fields.
  # Unknown fields will generate warnings (typo protection + version compatibility).
  harbor:
    # ==========================================================================
    # Agent settings (maps to Harbor AgentConfig)
    # ==========================================================================
    # Agent name - must be a valid Harbor AgentName (e.g., terminus-2, oracle)
    name: terminus-2
    # Max agent-environment turns before Harbor forces termination
    max_episodes: 64
    # Disable summarization, consistent with prior RL work
    enable_summarize: false
    # Store full message history for trajectory reconstruction
    store_all_messages: true
    # Disable episode-* folder creation to reduce disk I/O (SkyRL uses TrialResult directly)
    enable_episode_logging: false

    # Agent timeout overrides
    override_timeout_sec: 240        # Agent execution timeout (seconds)

    # ==========================================================================
    # Environment settings (maps to Harbor EnvironmentConfig)
    # ==========================================================================
    # Sandbox resources - adequate for most agentic tasks
    override_cpus: 1
    override_memory_mb: 2048
    override_storage_mb: 2048

    # ==========================================================================
    # Verifier settings (maps to Harbor VerifierConfig)
    # ==========================================================================
    verifier_override_timeout_sec: 120  # Override verifier timeout

    # ==========================================================================
    # Retry settings (maps to Harbor RetryConfig for QueueOrchestrator)
    # ==========================================================================
    max_retries: 3                 # Max retry attempts per trial
    min_wait_sec: 60.0              # Initial backoff delay (seconds)
    max_wait_sec: 600.0             # Maximum backoff delay
    wait_multiplier: 2.0           # Exponential backoff multiplier

    # Exception filtering - don't retry permanent failures
    exclude_exceptions:
      - AgentTimeoutError
      - VerifierTimeoutError
      - RewardFileNotFoundError
      - RewardFileEmptyError
      - VerifierOutputParseError
      - ContextLengthExceededError  # Permanent when enable_summarize=false

    # ==========================================================================
    # Orchestrator settings (QueueOrchestrator concurrency control)
    # ==========================================================================
    n_concurrent_trials: 16        # Number of parallel trial workers

    # ==========================================================================
    # Logging settings
    # ==========================================================================
    log_level: WARNING             # Harbor logging level (DEBUG, INFO, WARNING, ERROR)

    # ==========================================================================
    # Reward shaping settings (DISABLED - binary rewards)
    # ==========================================================================
    enable_reward_shaping: false   # Use original binary (0/1) verifier rewards

  # Model info for Harbor's hosted_vllm validation (token limits and costs)
  model_info:
    # Context budget: 32k total = 24k prompt + 8k generation
    max_input_tokens: 24576   # 24k - leaves 8k for generation
    max_output_tokens: 8192   # 8k - sufficient for most agent responses

# Trainer configuration
trainer:
  strategy: fsdp2
  algorithm:
    advantage_estimator: grpo
    # ==========================================================================
    # GSPO Policy Loss Configuration (KEY ABLATION)
    # ==========================================================================
    # GSPO (Group-wise Sequence Policy Optimization) policy loss
    # Each sequence contributes equally to the loss, regardless of length
    policy_loss_type: gspo
    # sequence_mean reduction is REQUIRED for GSPO (per the paper)
    # Per-sequence token-mean first, then batch-mean
    loss_reduction: sequence_mean
    # ==========================================================================
    use_kl_loss: true
    kl_loss_coef: 0.001
    grpo_norm_by_std: true
    # Clip range for policy updates
    eps_clip_low: 0.2
    eps_clip_high: 0.2

  # Training loop settings
  epochs: 10
  update_epochs_per_batch: 1

  # Batch sizes optimized for sync RL
  # IMPORTANT: train_batch_size must be >= total GPUs (data parallel size)
  train_batch_size: 16
  policy_mini_batch_size: 8  # 2 gradient steps per batch
  eval_batch_size: 32

  # Micro batch sizes - set to 1 for long context to avoid OOM
  micro_forward_batch_size_per_gpu: 1
  micro_train_batch_size_per_gpu: 1

  max_prompt_length: 999999

  # Evaluation and checkpointing
  eval_interval: 999999
  eval_before_train: false
  ckpt_interval: 10
  resume_mode: latest

  # Logging
  project_name: OpenThoughts-Agent
  log_level: INFO

  # Paths derived from experiments_dir/job_name if null
  run_name: null
  ckpt_path: null
  export_path: null

  # Policy optimizer - conservative LR for base model fine-tuning
  policy:
    optimizer_config:
      lr: 5.0e-7
      weight_decay: 0.01
      adam_betas: [0.9, 0.999]
      max_grad_norm: 1.0

  # Reference model - CPU offload to save GPU memory
  ref:
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true

  # Model placement - derived from CLI args (--num_nodes, --gpus_per_node)
  placement:
    colocate_all: true
    policy_num_nodes: null
    ref_num_nodes: null
    policy_num_gpus_per_node: null
    ref_num_gpus_per_node: null

# Generator (vLLM inference) configuration
generator:
  backend: vllm
  model_dtype: bfloat16

  # Tensor parallelism = 2 for 32k context with 8B model
  inference_engine_tensor_parallel_size: 2
  num_inference_engines: null

  # GRPO typically uses 4-8 samples per prompt for advantage estimation
  n_samples_per_prompt: 4
  eval_n_samples_per_prompt: 4

  # Memory utilization - aggressive but leave headroom for 32k KV cache
  gpu_memory_utilization: 0.90

  # Sequence limits for 32k context
  max_num_seqs: 64
  max_num_batched_tokens: 32768

  # Memory optimization for long contexts
  enable_prefix_caching: true
  enable_chunked_prefill: true

  # Engine settings
  run_engines_locally: true
  weight_sync_backend: nccl
  async_engine: true
  batched: true
  enable_http_endpoint: true

  # Multi-turn agentic conversation handling
  append_eos_token_after_stop_str_in_multi_turn: true
  max_turns: 64  # Match max_episodes

  # Sampling parameters for generation
  sampling_params:
    max_generate_length: 8192  # 8k - matches model_info.max_output_tokens
    temperature: 1.0
    top_p: 0.95
    top_k: -1  # Disabled

  # Engine initialization kwargs
  engine_init_kwargs:
    # Explicit context limit - ensures vLLM enforces 32k total context
    max_model_len: 32768
    custom_chat_template_chat_completion_path: chat_templates/qwen3_thinking_acc.jinja2

# Data paths (set via CLI --train_data, --val_data)
data:
  train_data: []
  val_data: ["open-thoughts/OpenThoughts-TB-dev"]
