#!/bin/bash
# =============================================================================
# proxychains-ng setup for transparent SOCKS proxying
# =============================================================================
# Installs proxychains-ng locally and configures it for the SSH tunnel.
#
# Usage:
#   # One-time install:
#   ./proxychains_setup.sh install
#
#   # Configure for a SOCKS proxy:
#   source proxychains_setup.sh configure <socks_host> <socks_port>
#
#   # Then run commands through the proxy:
#   proxychains4 python my_script.py
#
# =============================================================================

INSTALL_PREFIX="${PROXYCHAINS_PREFIX:-$HOME/.local}"
PROXYCHAINS_CONF="${PROXYCHAINS_CONF:-$HOME/.proxychains/proxychains.conf}"

install_proxychains() {
    echo "[proxychains] Installing proxychains-ng to $INSTALL_PREFIX"

    local TMPDIR=$(mktemp -d)
    cd "$TMPDIR"

    # Clone and build
    git clone https://github.com/rofl0r/proxychains-ng.git
    cd proxychains-ng

    ./configure --prefix="$INSTALL_PREFIX" --sysconfdir="$HOME/.proxychains"
    make -j$(nproc)
    make install

    # Cleanup
    cd /
    rm -rf "$TMPDIR"

    # Add to PATH if needed
    if [[ ":$PATH:" != *":$INSTALL_PREFIX/bin:"* ]]; then
        echo ""
        echo "[proxychains] Add to your .bashrc:"
        echo "  export PATH=\"$INSTALL_PREFIX/bin:\$PATH\""
    fi

    echo "[proxychains] ✓ Installed to $INSTALL_PREFIX/bin/proxychains4"
}

configure_proxychains() {
    local SOCKS_HOST="${1:?Error: SOCKS host required}"
    local SOCKS_PORT="${2:?Error: SOCKS port required}"

    mkdir -p "$(dirname "$PROXYCHAINS_CONF")"

    cat > "$PROXYCHAINS_CONF" << EOF
# proxychains-ng configuration
# Generated by proxychains_setup.sh

# Quiet mode (less output)
quiet_mode

# Proxy DNS requests through the proxy (important for internal hostnames)
proxy_dns

# Timeouts
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList - SOCKS5 proxy from SSH tunnel
[ProxyList]
socks5 ${SOCKS_HOST} ${SOCKS_PORT}
EOF

    echo "[proxychains] ✓ Configuration written to $PROXYCHAINS_CONF"
    echo "[proxychains] Proxy: socks5://${SOCKS_HOST}:${SOCKS_PORT}"

    # Export for convenience
    export PROXYCHAINS_CONF="$PROXYCHAINS_CONF"

    # Test if proxychains4 is available
    if command -v proxychains4 &> /dev/null; then
        echo "[proxychains] ✓ proxychains4 is available"
        echo ""
        echo "Usage:"
        echo "  proxychains4 python my_script.py"
        echo "  proxychains4 curl https://example.com"
    else
        echo "[proxychains] Warning: proxychains4 not in PATH"
        echo "  Run: ./proxychains_setup.sh install"
        echo "  Or:  export PATH=\"$INSTALL_PREFIX/bin:\$PATH\""
    fi
}

# Main
case "${1:-}" in
    install)
        install_proxychains
        ;;
    configure)
        shift
        configure_proxychains "$@"
        ;;
    *)
        echo "Usage:"
        echo "  $0 install                         # Install proxychains-ng locally"
        echo "  source $0 configure <host> <port>  # Configure for SOCKS proxy"
        ;;
esac
