# SkyRL Configuration: Qwen3 32B on 32x80GB GPUs (Binary Rewards, Async Training)
# Optimized for 32k context agentic RL with ASYNCHRONOUS training
#
# CHANGES (vs 8B config):
#   - Model: Qwen3-32B (~64GB bf16 weights)
#   - GPUs: 32x80GB (4 nodes x 8 GPUs)
#   - Inference: TP=2 (32B needs 2 GPUs per engine for 80GB)
#   - Policy/Ref: 16 GPUs each (FSDP2 sharding)
#
# REWARD MODE: Binary (0/1) - original verifier reward without shaping
# TRAINING MODE: Fully async - policy/ref/inference on dedicated GPU sets
#
# Hardware: 32 GPUs with 80GB VRAM each (e.g., 4x8 H100/A100-80GB)
# Model: Qwen3 32B Base (~64GB bf16 weights)
#
# GPU ALLOCATION (colocate_all=false):
#   - Policy model: 16 GPUs (4 nodes x 4 GPUs) - FSDP2 sharded
#   - Reference model: 16 GPUs (same as policy) - CPU offloaded
#   - Inference engines: 16 GPUs (8 engines x TP=2)
#
# ASYNC TRAINING BENEFITS:
#   - No waiting for slowest trajectory in batch
#   - Continuous policy updates as trajectories complete
#   - Better GPU utilization during generation
#   - Reduced wall-clock time for same number of samples
#
# CONTEXT BUDGET (32k total model context):
#   - max_generate_length: 8k tokens (agent responses)
#   - vLLM enforces total context <= max_model_len (32k)
#
# Key Design Decisions:
# - TP=2 for inference engines: 32B model needs 2 GPUs per engine on 80GB
# - 8 inference engines for parallelism (16 GPUs / TP=2)
# - batched=false: Each async worker handles its own requests
# - num_parallel_generation_workers=64: Matches mini_batch_size
# - n_samples_per_prompt=4: GRPO advantage estimation
#
# Usage:
#   python -m hpc.launch \
#       --job_type rl \
#       --rl_config qwen3_32b_32x80GB_thinking_bsc64_async_hilr.yaml \
#       --job_name qwen3_32b_agentic_async \
#       --train_data '["mlfoundations-dev/your-dataset"]' \
#       --model_path Qwen/Qwen3-32B \
#       --num_nodes 4

# SkyRL entrypoint module
entrypoint: examples.terminal_bench.entrypoints.main_tbench

# Hydra config groups (+ prefix in CLI)
config_groups:
  terminal_bench_config: terminal_bench

# Terminal bench / agentic environment settings
terminal_bench:
  # trials_dir: Directory for Harbor trial artifacts (derived from experiments_dir if null)
  trials_dir: null

  # Harbor configuration - schema-driven mapping to TrialConfig
  harbor:
    # ==========================================================================
    # Agent settings (maps to Harbor AgentConfig)
    # ==========================================================================
    name: terminus-2
    max_episodes: 64
    enable_summarize: false
    store_all_messages: true
    # Disable episode-* folder creation to reduce disk I/O (SkyRL uses TrialResult directly)
    enable_episode_logging: false

    # Agent timeout overrides
    override_timeout_sec: 240

    # ==========================================================================
    # Environment settings (maps to Harbor EnvironmentConfig)
    # ==========================================================================
    override_cpus: 1
    override_memory_mb: 2048
    override_storage_mb: 2048

    # ==========================================================================
    # Verifier settings (maps to Harbor VerifierConfig)
    # ==========================================================================
    verifier_override_timeout_sec: 120

    # ==========================================================================
    # Retry settings (maps to Harbor RetryConfig for QueueOrchestrator)
    # ==========================================================================
    max_retries: 3
    min_wait_sec: 60.0
    max_wait_sec: 600.0
    wait_multiplier: 2.0

    exclude_exceptions:
      - AgentTimeoutError
      - VerifierTimeoutError
      - RewardFileNotFoundError
      - RewardFileEmptyError
      - VerifierOutputParseError
      - ContextLengthExceededError

    # ==========================================================================
    # Orchestrator settings (QueueOrchestrator concurrency control)
    # ==========================================================================
    n_concurrent_trials: 32  # Increased for 32 GPUs

    # ==========================================================================
    # Logging settings
    # ==========================================================================
    log_level: WARNING

    # ==========================================================================
    # Reward shaping settings (DISABLED - binary rewards)
    # ==========================================================================
    enable_reward_shaping: false

    # ==========================================================================
    # Interleaved Thinking Settings
    # ==========================================================================
    interleaved_thinking: true
    extra_body:
      chat_template_kwargs:
        enable_thinking: true

  # Model info for Harbor's hosted_vllm validation (token limits and costs)
  model_info:
    max_input_tokens: 24576   # 24k - leaves 8k for generation
    max_output_tokens: 8192   # 8k - sufficient for most agent responses

# Trainer configuration
trainer:
  strategy: fsdp2
  algorithm:
    advantage_estimator: grpo
    use_kl_loss: true
    kl_loss_coef: 0.001
    grpo_norm_by_std: false  # Avoids division issues with binary rewards
    eps_clip_low: 0.2
    eps_clip_high: 0.2
    loss_reduction: token_mean

  # Training loop settings
  epochs: 10
  update_epochs_per_batch: 1

  # Batch sizes - async training requires train_batch_size == policy_mini_batch_size
  train_batch_size: 64
  policy_mini_batch_size: 64
  eval_batch_size: 32

  # Micro batch sizes - set to 1 for long context to avoid OOM
  micro_forward_batch_size_per_gpu: 1
  micro_train_batch_size_per_gpu: 1

  max_prompt_length: 999999

  # Evaluation and checkpointing
  eval_interval: 999999
  eval_before_train: false
  ckpt_interval: 10
  # IMPORTANT: resume_mode=none for async training - checkpoint resume causes data
  # consumption tracking mismatch (AssertionError: Unexpected number of consumed data UIDs)
  resume_mode: none

  # Logging
  project_name: OpenThoughts-Agent
  log_level: INFO
  tracker_commit_each_step: true

  # Paths derived from experiments_dir/job_name if null
  run_name: null
  ckpt_path: null
  export_path: null

  # Policy optimizer - Higher LR for faster adaptation
  policy:
    optimizer_config:
      lr: 1.0e-6
      weight_decay: 0.01
      adam_betas: [0.9, 0.999]
      max_grad_norm: 1.0

  # Reference model - CPU offload to save GPU memory
  ref:
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true

  # ==========================================================================
  # ASYNC TRAINING: Model placement (colocate_all=false)
  # ==========================================================================
  # For 32 GPUs with 32B model:
  # - Policy: 16 GPUs (4 nodes x 4 GPUs)
  # - Ref: 16 GPUs (same as policy, CPU offloaded)
  # - Inference: 16 GPUs (8 engines x TP=2)
  placement:
    colocate_all: false
    policy_num_nodes: 4
    ref_num_nodes: 4
    policy_num_gpus_per_node: 4
    ref_num_gpus_per_node: 4

  # ==========================================================================
  # ASYNC TRAINING: Fully async generation settings
  # ==========================================================================
  fully_async:
    # Constraint: mini_batch_size <= num_parallel_generation_workers <= mini_batch_size * (max_staleness_steps + 1)
    num_parallel_generation_workers: 64

# Generator (vLLM inference) configuration
generator:
  backend: vllm
  model_dtype: bfloat16

  # ==========================================================================
  # ASYNC TRAINING: Inference engine configuration
  # ==========================================================================
  # TP=2 for 32B model (needs ~32GB per GPU for weights on 80GB cards)
  inference_engine_tensor_parallel_size: 2
  # 8 engines x TP=2 = 16 GPUs dedicated to inference
  num_inference_engines: 8

  # GRPO samples per prompt
  n_samples_per_prompt: 4
  eval_n_samples_per_prompt: 4

  # Memory utilization - slightly lower for larger model
  gpu_memory_utilization: 0.85

  # Sequence limits for 32k context
  # With TP=2, each engine has more memory for KV cache
  max_num_seqs: 32
  max_num_batched_tokens: 32768

  # Memory optimization for long contexts
  enable_prefix_caching: true
  enable_chunked_prefill: true

  # ==========================================================================
  # ASYNC TRAINING: Engine settings
  # ==========================================================================
  run_engines_locally: true
  weight_sync_backend: nccl
  async_engine: true
  batched: false
  enable_http_endpoint: true

  # Multi-turn agentic conversation handling
  append_eos_token_after_stop_str_in_multi_turn: true
  max_turns: 64

  # Sampling parameters for generation
  sampling_params:
    max_generate_length: 8192
    temperature: 1.0
    top_p: 0.95
    top_k: -1

  # Engine initialization kwargs
  engine_init_kwargs:
    # Explicit context limit - ensures vLLM enforces 32k total context
    max_model_len: 32768
    custom_chat_template_chat_completion_path: chat_templates/qwen3_thinking_acc.jinja2

# Data paths (set via CLI --train_data, --val_data)
data:
  train_data: []
  val_data: ["open-thoughts/OpenThoughts-TB-dev"]
