# SkyRL Configuration: Qwen3 1.7B on 4x80GB GPUs
# Optimized for 32k context agentic RL with synchronous training
#
# Hardware: 4 GPUs with 80GB VRAM each (e.g., 1x4 H100/A100-80GB)
# Model: Qwen3 1.7B Base (~3.4GB bf16 weights)
#
# CONTEXT BUDGET (32k total model context):
#   - max_generate_length: 8k tokens (agent responses)
#   - vLLM enforces total context <= max_model_len (32k)
#
# vLLM enforces prompt + generation <= max_model_len, so we must budget.
# For multi-turn agentic tasks, prompts grow with history - enable_summarize
# helps compress old turns to stay within budget.
#
# Key Design Decisions:
# - TP=1 for inference engines: 4 engines with 80GB each
#   1.7B model is small enough for single-GPU inference with 32k context
# - Moderate train_batch_size (8): Good for 4 GPUs with 2 gradient steps
# - Aggressive memory settings: 0.92 utilization (smaller model = more KV cache room)
# - GRPO with 4 samples: Good gradient signal for policy improvement
#
# Usage:
#   python -m hpc.launch \
#       --job_type rl \
#       --rl_config qwen3_1.7b_4x80GB.yaml \
#       --job_name qwen3_1.7b_agentic \
#       --train_data '["mlfoundations-dev/your-dataset"]' \
#       --model_path Qwen/Qwen3-1.7B \
#       --num_nodes 1

# SkyRL entrypoint module
entrypoint: examples.terminal_bench.entrypoints.main_tbench

# Hydra config groups (+ prefix in CLI)
config_groups:
  terminal_bench_config: terminal_bench

# Terminal bench / agentic environment settings
terminal_bench:
  # trials_dir: Directory for Harbor trial artifacts (derived from experiments_dir if null)
  trials_dir: null

  # Harbor configuration - schema-driven mapping to TrialConfig
  # See examples/terminal_bench/harbor_config.py for full list of supported fields.
  # Unknown fields will generate warnings (typo protection + version compatibility).
  harbor:
    # ==========================================================================
    # Agent settings (maps to Harbor AgentConfig)
    # ==========================================================================
    # Agent name - must be a valid Harbor AgentName (e.g., terminus-2, oracle)
    name: terminus-2
    # Max agent-environment turns before Harbor forces termination
    max_episodes: 16
    # Disable summarization, consistent with prior RL work
    enable_summarize: false
    # Store full message history for trajectory reconstruction
    store_all_messages: true
    # Disable episode-* folder creation to reduce disk I/O (SkyRL uses TrialResult directly)
    enable_episode_logging: false

    # Agent timeout overrides
    override_timeout_sec: 240        # Agent execution timeout (seconds)
    # override_setup_timeout_sec: 120  # Agent setup timeout
    # max_timeout_sec: 1800          # Cap timeout (useful for runaway tasks)

    # ==========================================================================
    # Environment settings (maps to Harbor EnvironmentConfig)
    # ==========================================================================
    # Sandbox resources - adequate for most agentic tasks
    override_cpus: 1
    override_memory_mb: 2048
    override_storage_mb: 2048
    # override_gpus: 0              # GPU allocation per sandbox
    # environment_type: daytona     # Environment backend (daytona, docker, modal)

    # ==========================================================================
    # Trial-level settings (maps to Harbor TrialConfig)
    # ==========================================================================
    # timeout_multiplier: 1.0       # Multiply all timeouts by this factor

    # ==========================================================================
    # Verifier settings (maps to Harbor VerifierConfig)
    # ==========================================================================
    # verifier_disable: false       # Disable verification (for debugging)
    verifier_override_timeout_sec: 120  # Override verifier timeout

    # ==========================================================================
    # Retry settings (maps to Harbor RetryConfig for QueueOrchestrator)
    # ==========================================================================
    max_retries: 3                 # Max retry attempts per trial
    min_wait_sec: 60.0              # Initial backoff delay (seconds)
    max_wait_sec: 600.0             # Maximum backoff delay
    wait_multiplier: 2.0           # Exponential backoff multiplier

    # Exception filtering - don't retry permanent failures
    # We add ContextLengthExceededError since summarization is disabled
    exclude_exceptions:
      - AgentTimeoutError
      - VerifierTimeoutError
      - RewardFileNotFoundError
      - RewardFileEmptyError
      - VerifierOutputParseError
      - ContextLengthExceededError  # Permanent when enable_summarize=false

    # ==========================================================================
    # Orchestrator settings (QueueOrchestrator concurrency control)
    # ==========================================================================
    n_concurrent_trials: 16        # Number of parallel trial workers

    # ==========================================================================
    # Logging settings
    # ==========================================================================
    log_level: WARNING             # Harbor logging level (DEBUG, INFO, WARNING, ERROR)

    # ==========================================================================
    # Reward shaping settings (partial credit for test pass ratios)
    # ==========================================================================
    enable_reward_shaping: true    # Enable reward shaping based on test output
    reward_parser: null            # Auto-detect (pytest, unittest, generic)
    reward_shaper: pass_ratio      # Simple mean: passed_tests / total_tests
    reward_shaping_fallback: true  # Fall back to original reward if parsing fails

  # Model info for Harbor's hosted_vllm validation (token limits and costs)
  model_info:
    # Context budget: 32k total = 24k prompt + 8k generation
    # Prompts grow with conversation history, so reserve headroom for generation
    max_input_tokens: 24576   # 24k - leaves 8k for generation
    max_output_tokens: 8192   # 8k - sufficient for most agent responses

# Trainer configuration
trainer:
  strategy: fsdp2
  algorithm:
    advantage_estimator: grpo
    use_kl_loss: true
    # GRPO-specific settings
    kl_loss_coef: 0.001
    grpo_norm_by_std: true
    # Clip range for policy updates
    eps_clip_low: 0.2
    eps_clip_high: 0.2
    # Token-level loss for better gradient signal on long sequences
    loss_reduction: token_mean

  # Training loop settings
  epochs: 10
  update_epochs_per_batch: 1

  # Batch sizes optimized for 4 GPUs
  # train_batch_size must be >= total GPUs (data parallel size)
  # For 1 node x 4 GPUs = 4 GPUs, use train_batch_size >= 4
  train_batch_size: 8
  policy_mini_batch_size: 4  # 2 gradient steps per batch
  eval_batch_size: 16

  # Micro batch sizes - set to 1 for long context to avoid OOM
  micro_forward_batch_size_per_gpu: 1
  micro_train_batch_size_per_gpu: 1

  max_prompt_length: 999999

  # Evaluation and checkpointing
  eval_interval: 10
  eval_before_train: false
  ckpt_interval: 5
  resume_mode: latest

  # Logging
  project_name: OpenThoughts-Agent
  log_level: INFO  # SkyRL logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

  # Paths derived from experiments_dir/job_name if null
  run_name: null
  ckpt_path: null
  export_path: null

  # Policy optimizer - conservative LR for base model fine-tuning
  policy:
    optimizer_config:
      lr: 1.0e-6  # Slightly higher LR for smaller model
      weight_decay: 0.01
      adam_betas: [0.9, 0.999]
      # Gradient clipping important for long sequences
      max_grad_norm: 1.0

  # Reference model - CPU offload to save GPU memory
  ref:
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true

  # Model placement - derived from CLI args (--num_nodes, --gpus_per_node)
  placement:
    colocate_all: true
    # Derived from CLI --num_nodes
    policy_num_nodes: null
    ref_num_nodes: null
    # Derived from CLI --gpus_per_node (cluster-specific: 4 for ZIH, 8 for TACC H100s)
    policy_num_gpus_per_node: null
    ref_num_gpus_per_node: null

# Generator (vLLM inference) configuration
generator:
  backend: vllm
  model_dtype: bfloat16

  # Tensor parallelism = 1 for 1.7B model (fits easily on single GPU)
  # This gives us 4 inference engines (4 GPUs / TP=1)
  # Each engine has 80GB for model (~3.4GB) + KV cache (~76GB available)
  inference_engine_tensor_parallel_size: 1
  # Computed automatically: (num_nodes * gpus_per_node) / tensor_parallel_size
  num_inference_engines: null

  # GRPO typically uses 4-8 samples per prompt for advantage estimation
  n_samples_per_prompt: 4
  eval_n_samples_per_prompt: 4

  # Memory utilization - more aggressive for smaller model
  gpu_memory_utilization: 0.92

  # Sequence limits for 32k context (24k prompt + 8k gen)
  # max_num_seqs: concurrent sequences per engine
  # Can be higher for smaller model (less memory per sequence)
  max_num_seqs: 128
  # max_num_batched_tokens: tokens processed per batch
  # Should accommodate at least one full sequence (32k) with some headroom
  max_num_batched_tokens: 32768

  # Memory optimization for long contexts
  enable_prefix_caching: true
  enable_chunked_prefill: true

  # Engine settings
  run_engines_locally: true
  weight_sync_backend: nccl
  async_engine: true
  batched: true
  enable_http_endpoint: true

  # Multi-turn agentic conversation handling
  append_eos_token_after_stop_str_in_multi_turn: true
  max_turns: 32  # Match max_episodes

  # Sampling parameters for generation
  sampling_params:
    # Context budget: 32k total = 24k prompt + 8k generation
    # This caps generation to stay within model's max_model_len
    max_generate_length: 8192  # 8k - matches model_info.max_output_tokens
    # Temperature 1.0 for exploration during training
    temperature: 1.0
    top_p: 0.95
    top_k: -1  # Disabled

  # Engine initialization kwargs - passed directly to vLLM/SGLang engine
  # WARNING: Many kwargs are set by SkyRL internally (trust_remote_code, enforce_eager, etc.)
  # The launcher validates this at parse time and will error with a full list if you set forbidden keys.
  # SAFE TO SET: custom_chat_template_*, kv_cache_dtype, quantization, cpu_offload_gb, etc.
  engine_init_kwargs:
    # Explicit context limit - ensures vLLM enforces 32k total context
    max_model_len: 32768
    # Chat template for Qwen3 Base model (path relative to working directory or absolute)
    custom_chat_template_chat_completion_path: chat_templates/qwen3_thinking_acc.jinja2

# Data paths (set via CLI --train_data, --val_data)
data:
  train_data: []
  val_data: ["open-thoughts/OpenThoughts-TB-dev"]
